-- ============================================================================
-- SAMPLE DATA - INSERT PROJECTS
-- ============================================================================
-- This inserts the sample projects from your Excel file
-- Real embeddings would be generated by OpenAI - these are placeholders
-- ============================================================================

-- Project 1: Adidas LFS Showroom Support
INSERT INTO projects (
    client, pa_number, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned,
    source_file_path, notes
) VALUES (
    'Adidas',
    'PA251409',
    'Sportswear / Lifestyle Retail',
    'France, Italy',
    'LFS Showroom Support',
    'Seasonal sell-in support and showroom enablement',
    'event_apparel',
    'Example 6 week visitor window',
    'signed',
    'ongoing',
    2025,
    ARRAY['events', 'running', 'retail activation', 'showroom', 'GTM', 'partner engagement', 'Paris', 'Milan', 'product display', 'brand experience'],
    ARRAY['Category showrooms (Originals, Football, Running, Outdoor, Motorsport, Training, Stella McCartney, Sportswear)'],
    ARRAY['1000+ visitors over 6 weeks', 'daily 30+ BA setup'],
    'PA251409_RFP_LFS Showroom Support',
    'No Feedback Yet'
);

-- Project 2: Hisense IFA Partner Event
INSERT INTO projects (
    client, pa_number, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned,
    source_file_path, notes
) VALUES (
    'Hisense',
    'PA250667',
    'Consumer Electronics / Home Appliances',
    'IFA Berlin – Germany',
    'Hisense Europe IFA Partner Event 2025',
    'Strengthen Partner Relationship',
    'event_sponsorship',
    '1 evening (IFA week)',
    'signed',
    'ongoing',
    2025,
    ARRAY['partner engagement', 'IFA', 'consumer electronics', 'football sponsorship', 'experiential marketing', 'hospitality', 'Berlin', 'innovation', 'togetherness'],
    ARRAY['Venue (Haus Zenner)', 'Water Taxi transfers', 'LED walls', 'branded stage design'],
    ARRAY['40 pax per Water Taxi trip', '100s of VIP partner guests'],
    'PA250667_RFP_Hisense_IFA Partners Event 2025',
    'Event designed as a holistic hospitality'
);

-- Project 3: Adidas Vending Machine Activation
INSERT INTO projects (
    client, pa_number, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned,
    source_file_path, notes
) VALUES (
    'Adidas',
    'PA251416',
    'Sportswear / Lifestyle Retail',
    'The United States, Canada, Mexico',
    'Vending Machine Activation',
    'Experiential PR',
    'experiential_activation',
    NULL,
    'not_signed',
    'not_executed',
    NULL,
    ARRAY['retail', 'activation', 'vending', 'sampling', 'experiential', 'lifestyle'],
    ARRAY['activation mockups', '3D renders', 'deck'],
    ARRAY['impressions (est.)', 'footfall (if provided)'],
    'pitches/adidas_vending_machine.pdf',
    'EXAMPLE — confirm outcome and rationale if documented.'
);

-- Project 4: UEFA Women's Football Business Case
INSERT INTO projects (
    client, pa_number, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned,
    source_file_path, notes
) VALUES (
    'UEFA',
    'PA251266',
    'Sports / Football (Women''s Football)',
    'Lisbon 2025 + multi-country scope for 2026+',
    'UEFA Business Case for Women''s Football – Lisbon 2025',
    'Align clubs, federations, sponsors, and partners on the business potential of women''s football',
    'event_sponsorship',
    '1 Day Conference (24 may 2025)',
    'signed',
    'completed',
    2025,
    ARRAY['UEFA', 'women''s football', 'conference', 'business case', 'stakeholder alignment', 'sports development', 'gender equity', 'Lisbon'],
    ARRAY['Venue (Lisbon Botanical Gardens greenhouse, 300+ plant species)', '160-module LED screen'],
    ARRAY['186 VIP guests', '97 staff', '8-hour setup', 'dismantle within 90 mins', '4 giant banners', '9 flags', '25 cubes', '2 plinths', 'trophy stage', 'extensive social/media coverage'],
    'PA251266 UEFA Business Case Women Oslo',
    'High-profile UEFA stakeholder conference; positioned as a milestone in women''s football growth.'
);

-- ============================================================================
-- SAMPLE AUDIENCE SEGMENTS
-- ============================================================================

-- Get project IDs for linking (adjust UUIDs after insertion)
DO $$
DECLARE
    adidas_project_id UUID;
    hisense_project_id UUID;
BEGIN
    -- Get Adidas project ID
    SELECT id INTO adidas_project_id FROM projects WHERE pa_number = 'PA251409' LIMIT 1;
    
    -- Get Hisense project ID
    SELECT id INTO hisense_project_id FROM projects WHERE pa_number = 'PA250667' LIMIT 1;
    
    -- Insert audience segments
    INSERT INTO audience_segments (project_id, segment_id, segment_name, traits, relevant_keywords) VALUES
        (adidas_project_id, 'aud001', 'Sneakerheads', 'Fashion-forward, trend-sensitive', ARRAY['Sneaker culture', 'Product launches']),
        (hisense_project_id, 'aud002', 'Digital-Savvy Creators', 'Active on TikTok and Twitch', ARRAY['Digital crossover', 'Streamer activations']);
END $$;

-- ============================================================================
-- ADD MORE SAMPLE PROJECTS (For testing)
-- ============================================================================

-- Project 5: Nike Digital Campaign
INSERT INTO projects (
    client, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned
) VALUES (
    'Nike',
    'Sportswear / Lifestyle Retail',
    'Global',
    'Just Do It Digital Refresh',
    'Reinvigorate brand messaging for Gen-Z audience',
    'digital_social',
    '12 weeks',
    'signed',
    'completed',
    2024,
    ARRAY['digital', 'social media', 'Gen-Z', 'brand refresh', 'influencer marketing', 'TikTok', 'Instagram'],
    ARRAY['Video content', 'Influencer partnerships', 'Social media toolkit'],
    ARRAY['10M+ impressions', '500K+ engagements', '50+ influencer activations']
);

-- Project 6: Puma Motorsport Launch
INSERT INTO projects (
    client, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned
) VALUES (
    'Puma',
    'Sportswear / Lifestyle Retail',
    'Europe',
    'F1 Collaboration Launch Event',
    'Launch exclusive motorsport collection with F1 partnership',
    'event_sponsorship',
    '1 day event',
    'signed',
    'completed',
    2024,
    ARRAY['motorsport', 'F1', 'collaboration', 'launch event', 'exclusive collection', 'racing'],
    ARRAY['Event venue', 'F1 car display', 'VIP hospitality', 'Collection showcase'],
    ARRAY['500+ VIP attendees', '2M+ social media reach', 'Sell-out collection']
);

-- Project 7: Adidas Sustainability Campaign
INSERT INTO projects (
    client, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned
) VALUES (
    'Adidas',
    'Sportswear / Lifestyle Retail',
    'Global',
    'End Plastic Waste Initiative',
    'Promote sustainable products and environmental commitment',
    'branding_identity',
    '6 months',
    'signed',
    'ongoing',
    2024,
    ARRAY['sustainability', 'environment', 'recycled materials', 'ocean plastic', 'green initiative'],
    ARRAY['Campaign materials', 'Product line', 'Educational content', 'Partnership announcements'],
    ARRAY['30% increase in sustainable product sales', '5M+ awareness impressions', '50+ media features']
);

-- Project 8: New Balance Retail Activation
INSERT INTO projects (
    client, industry, market, campaign_name,
    objective, strategy_tactic, campaign_length,
    deal_status, project_status, year_context,
    keywords, assets, kpis_mentioned
) VALUES (
    'New Balance',
    'Sportswear / Lifestyle Retail',
    'United States',
    'Made in USA Store Experience',
    'Create immersive retail experience highlighting craftsmanship',
    'ooh_activation',
    '3 months',
    'not_signed',
    'not_executed',
    2024,
    ARRAY['retail', 'experiential', 'craftsmanship', 'Made in USA', 'store design', 'brand heritage'],
    ARRAY['Store design mockups', 'Interactive displays', 'Product showcases'],
    ARRAY['Estimated 50K+ store visitors', 'Projected 20% sales lift']
);

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- View all projects
-- SELECT client, campaign_name, deal_status, project_status, year_context FROM projects ORDER BY created_at DESC;

-- Count projects by status
-- SELECT deal_status, COUNT(*) FROM projects GROUP BY deal_status;

-- Count projects by client
-- SELECT client, COUNT(*) FROM projects GROUP BY client ORDER BY COUNT(*) DESC;

-- View all audience segments
-- SELECT s.segment_name, p.client, p.campaign_name 
-- FROM audience_segments s 
-- JOIN projects p ON s.project_id = p.id;
